repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check --fix app/
        language: system
        types: [python]
        stages: [manual]

      - id: black
        name: black
        entry: poetry run black app/
        language: system
        types: [python]
        stages: [manual]

      - id: mypy
        name: mypy
        entry: bash -c 'export MYPYPATH=app && poetry run mypy app/'
        require_serial: true
        language: system
        types: [python]
        stages: [manual]  

      - id: bandit
        name: bandit
        entry: poetry run bandit -r .
        language: system
        types: [python]
        stages: [manual] 
