repos:
  - repo: local
    hooks:
      # - id: ruff
      #   name: ruff
      #   entry: poetry run ruff --check .
      #   language: system
      #   types: [python]

      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]

      # - id: mypy
      #   name: mypy
      #   entry: poetry run mypy .
      #   language: system
      #   types: [python]

      # - id: bandit
      #   name: bandit
      #   entry: poetry run bandit -r .
      #   language: system
      #   types: [python]
